module.exports = {
  valid_words: [
    "pizza",
    "chicken",
    "fried chicken",
    "friedchicken",
    "ice cream",
    "icecream",
    "mcdonalds",
    "mcd",
    "popeyes",
    "rice",
    "sushi",
    "bubbletea",
    "bbt",
    "boba tea",
    "chatime",
    "shwarma",
    "free food",
    "food for free",
    "banh mi boys",
    "banhmiboys",
    "beef",
    "ramen",
    "noodle",
    "popcorn",
    "candy",
    "chocolate",
    "falafel",
    "chowmein",
    "chow mein",
    "burger",
    "hot dogs",
    "hotdogs",
    "hotdog",
    "patty",
    "patties",
    "burgers",
    "hamburgers",
    "hamburger",
    "chickenburger",
    "chicken burger",
    "chicken burgers",
    "chickenburgers",
    "veggie",
    "corn",
    "cornbeef",
    "taco",
    "tacos",
    "soup",
    "fish",
    "fish and chips",
    "fishandchips",
    "fish&chips",
    "donuts",
    "coffee",
    "timbits",
    "drinks",
    "lunch",
    "dinner",
    "breakfast",
    "brunch",
    "apples",
    "oranges",
    "bananas",
    "banana",
    "frap",
    "frappuccino",
    "mocha",
    "mochaccino",
    "cappuccino",
    "pear",
    "water",
    "ice",
    "biscuit",
    "double double",
    "timmies",
    "lemonade"
  ],
  invalid_words: [
    "westjet",
    "air canada",
    "aircanada",
    "porter",
    "bogo",
    "buy one get one",
    "bogo pizza",
    "owe",
    "coupon",
    "with the purchase of",
  ]
}
